update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,21 +7,20 @@ env:
   FLUTTER_VERSION: '3.35.4'
 
 jobs:
-  # JOB 1: ANDROID
+    # JOB 1: ANDROID
   build-android:
     name: Build Android
-    runs-on: ubuntu-latest
-    # Map secrets here so they are accessible as env variables
+    runs-on: windows-latest
     env:
       HAS_KEYSTORE: ${{ secrets.KEY_STORE != '' }}
     steps:
       - uses: actions/checkout@v4
-      
+
       - name: Max Cache Android
         uses: actions/cache@v4
         with:
           path: |
-            ~/.pub-cache
+            ${{ env.LOCALAPPDATA }}\Pub\Cache
             .dart_tool/
             build/app/outputs/flutter-apk/
           key: ${{ runner.os }}-android-v3-${{ github.sha }}
@@ -39,90 +38,131 @@ jobs:
           flutter-version: ${{ env.FLUTTER_VERSION }}
           cache: true
 
+      - name: Install Dependencies
+        run: flutter pub get
+
       - name: Extract Version
+        shell: powershell
         run: |
-          VER=$(grep -E '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
-          echo "VERSION=$VER" >> $GITHUB_ENV
+          $vLine = Select-String -Path pubspec.yaml -Pattern '^version:\s*(\S+)' | Select-Object -First 1
+          if (-not $vLine) { Write-Error 'version not found in pubspec.yaml'; exit 1 }
+          $ver = $vLine.Matches[0].Groups[1].Value.Split('+')[0]
+          echo "VERSION=$ver" >> $env:GITHUB_ENV
 
       - name: Create Keystore
         if: env.HAS_KEYSTORE == 'true'
+        shell: powershell
         run: |
-          echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/bloomee.jks
-          printf "keyPassword=${{ secrets.KEY_PASSWORD }}\nstorePassword=${{ secrets.STORE_PASSWORD }}\nkeyAlias=${{ secrets.KEY_ALIAS }}\nstoreFile=bloomee.jks" > android/key.properties
+          $b64 = "${{ secrets.KEY_STORE }}"
+          $bytes = [Convert]::FromBase64String($b64)
+          [IO.File]::WriteAllBytes("./android/bloomee.jks", $bytes)
+          "keyPassword=${{ secrets.KEY_PASSWORD }}" | Out-File -FilePath ./android/key.properties -Encoding ascii
+          "storePassword=${{ secrets.STORE_PASSWORD }}" | Out-File -FilePath ./android/key.properties -Append -Encoding ascii
+          "keyAlias=${{ secrets.KEY_ALIAS }}" | Out-File -FilePath ./android/key.properties -Append -Encoding ascii
 
-      - name: Build APK (Signed)
-        if: env.HAS_KEYSTORE == 'true'
+      - name: Build APK
         run: flutter build apk --release --split-per-abi --build-number ${{ github.run_number }}
 
-      - name: Build APK (Debug)
-        if: env.HAS_KEYSTORE != 'true'
-        run: flutter build apk --debug --split-per-abi --build-number ${{ github.run_number }}
+      - name: Verify Sign
+        shell: powershell
+        run: |
+          $buildToolsDir = Get-ChildItem "$env:ANDROID_HOME\build-tools" | Where-Object { $_.PSIsContainer } | Sort-Object Name -Descending | Select-Object -First 1
+          Write-Host "Using build tools version: $($buildToolsDir.Name)"
+          & "$($buildToolsDir.FullName)\apksigner.bat" verify build/app/outputs/flutter-apk/app-release.apk
+          & "$($buildToolsDir.FullName)\apksigner.bat" verify build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
+          & "$($buildToolsDir.FullName)\apksigner.bat" verify build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
+          & "$($buildToolsDir.FullName)\apksigner.bat" verify build/app/outputs/flutter-apk/app-x86_64-release.apk
 
       - name: Rename APKs
+        shell: powershell
         run: |
-          cd build/app/outputs/flutter-apk/
-          for file in *.apk; do
-            mv "$file" "bloomee_v${{ env.VERSION }}+${{ github.run_number }}_${file/-release/}"
-          done
+          Rename-Item -Path "build/app/outputs/flutter-apk/app-release.apk" -NewName "bloomee_tunes_android_v$env:VERSION+${{ github.run_number }}_universal.apk"
+          Rename-Item -Path "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk" -NewName "bloomee_tunes_android_v$env:VERSION+${{ github.run_number }}_armeabi-v7a.apk"
+          Rename-Item -Path "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" -NewName "bloomee_tunes_android_v$env:VERSION+${{ github.run_number }}_arm64-v8a.apk"
+          Rename-Item -Path "build/app/outputs/flutter-apk/app-x86_64-release.apk" -NewName "bloomee_tunes_android_v$env:VERSION+${{ github.run_number }}_x86_64.apk"
 
       - name: Upload Android Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: Release-Android
-          path: build/app/outputs/flutter-apk/*.apk
+          path: |
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_universal.apk
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_armeabi-v7a.apk
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_arm64-v8a.apk
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_x86_64.apk
 
-      - name: Release Android
+      - name: Create Android Release
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "build/app/outputs/flutter-apk/*.apk"
+          artifacts: |
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_universal.apk
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_armeabi-v7a.apk
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_arm64-v8a.apk
+            build/app/outputs/flutter-apk/bloomee_tunes_android_v${{ env.VERSION }}+${{ github.run_number }}_x86_64.apk
           tag: v${{ env.VERSION }}+${{ github.run_number }}
           token: ${{ secrets.SECRET_KEY || secrets.GITHUB_TOKEN }}
+          prerelease: true
           allowUpdates: true
 
-  # JOB 2: WINDOWS
+    # JOB 2: WINDOWS
   build-windows:
     name: Build Windows
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
+
       - name: Max Cache Windows
         uses: actions/cache@v4
         with:
           path: |
             ${{ env.LOCALAPPDATA }}\Pub\Cache
             build/windows/x64/runner/Release/
-          key: ${{ runner.os }}-win-v3-${{ github.sha }}
-          restore-keys: ${{ runner.os }}-win-v3-
+          key: ${{ runner.os }}-windows-v3-${{ github.sha }}
+          restore-keys: ${{ runner.os }}-windows-v3-
 
       - uses: subosito/flutter-action@v2
         with:
           flutter-version: ${{ env.FLUTTER_VERSION }}
           cache: true
 
-      - name: Build & Zip
+      - name: Install Dependencies
+        run: flutter pub get
+
+      - name: Extract Version
         shell: powershell
         run: |
-          $ver = (Select-String -Path pubspec.yaml -Pattern '^version:\s*(\S+)').Matches[0].Groups[1].Value.Split('+')[0]
-          flutter build windows --release --build-number ${{ github.run_number }}
-          Rename-Item -Path "build/windows/x64/runner/Release/bloomee.exe" -NewName "Bloomee.exe"
-          Compress-Archive -Path build/windows/x64/runner/Release/* -Destination "bloomee_windows_v$ver.zip"
-          echo "VER=$ver" >> $env:GITHUB_ENV
+          $vLine = Select-String -Path pubspec.yaml -Pattern '^version:\s*(\S+)' | Select-Object -First 1
+          if (-not $vLine) { Write-Error 'version not found in pubspec.yaml'; exit 1 }
+          $ver = $vLine.Matches[0].Groups[1].Value.Split('+')[0]
+          echo "VERSION=$ver" >> $env:GITHUB_ENV
+
+      - name: Build Windows App
+        run: flutter build windows --release --build-number ${{ github.run_number }}
+
+      - name: Rename Windows binary
+        shell: powershell
+        run: Rename-Item -Path "build/windows/x64/runner/Release/bloomee.exe" -NewName "Bloomee.exe"
+
+      - name: ZIP build
+        shell: powershell
+        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath build/windows/x64/bloomee_tunes_windows_x64_v${{ env.VERSION }}+${{ github.run_number }}.zip
 
       - name: Upload Windows Artifact
         uses: actions/upload-artifact@v4
         with:
           name: Release-Windows
-          path: "*.zip"
+          path: build/windows/x64/bloomee_tunes_windows_x64_v${{ env.VERSION }}+${{ github.run_number }}.zip
 
-      - name: Release Windows
+      - name: Create Windows Release
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "*.zip"
-          tag: v${{ env.VER }}+${{ github.run_number }}
+          artifacts: build/windows/x64/bloomee_tunes_windows_x64_v${{ env.VERSION }}+${{ github.run_number }}.zip
+          tag: v${{ env.VERSION }}+${{ github.run_number }}
           token: ${{ secrets.SECRET_KEY || secrets.GITHUB_TOKEN }}
+          prerelease: true
           allowUpdates: true
 
-  # JOB 3: MACOS
+# JOB 3: MACOS
   build-macos:
     name: Build macOS
     runs-on: macos-latest
